# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec6f507022c8f0101dcc00e5ab4971587f606e3fb6f49375f446d5ffec6618472db26425d55a6246727ecc521c39dcddfd0083ff8d8914af4551942f6ce038ee

test:
  secret_key_base: bb9baed7097dfa81572eeccaad40a7d4272b2a01f02dd9a76b40690e826d035236a564aa6f4e5e3f2dd8b40b26fc2805a26ee7a7ee84a5b669d24ff2c33d6c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
